### ISSUE TITLE
Git repo not updated in docs

### ISSUE THREAD

**Issue by neokree** [Web3Auth/web3auth-docs#125]
Hello

Here: https://docs.web3auth.io/quick-start?lang=flutter&chain=eth&customAuthentication=no&whitelabel=no&customLogin=no   
You can see that the repository for the import points to `torusresearch` user, not Web3Auth. 
If I apply the docs exactly as told the pub get doesn't finish fetching because the repository doesn't exist (or is a private one).

Please update the docs to link it to this repo, thank you

**Comment by yashovardhan** [comment]
Hey @neokree 

I'm closing this issue for now. Feel free to open it up again if you're facing this issue, or open a new [discussion](https://github.com/Web3Auth/Web3Auth/discussions) regarding this.
